# Generated by Django 4.2.20 on 2025-03-25 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image', models.ImageField(upload_to='original_images/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='processed_images/')),
            ],
        ),
    ]
